; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino

monitor_speed = 921600
upload_port = COM3

build_flags = 
    ; Optimization for code execution speed
    -O3
    ; Disabling unnecessary system logs that slow down the processor
    -D CORE_DEBUG_LEVEL=0
    ; CRUCIAL FOR WROVER: Enabling external RAM (PSRAM)
    -D BOARD_HAS_PSRAM
    ; Hardware patch for stability during intensive memory transfers
    -mfix-esp32-psram-cache-issue


    ; --- Network configuration ---
    ; Setting the Wi-Fi mode: 0 for Station (STA), 1 for Access Point (AP)
    -D IS_ESPY_NEXUS_AP=0
    
    ; STA
    -D WIFI_STA_SSID=\"Your Wi-Fi SSID\"
    -D WIFI_STA_PASS=\"YourSuperSecretPassword\"
    
    ; AP
    -D WIFI_AP_SSID=\"ESPy_Nexus_AP\"
    -D WIFI_AP_PASS=\"YourSuperSecretPassword\"
    
    ; UDP
    -D UDP_PORT=8080
